name: Lighthouse CI
on: [push]
jobs:
    lhci:
        name: Lighthouse
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: Install Dependencies & Build Project
              run: |
                  npm install
                  npm run build
            - name: Run Lighthouse CI
              run: |
                  npm install -g @lhci/cli@0.7.x
                  lhci autorun
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LIGHTHOUSE_CI_GITHUB_APP_TOKEN }}